name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # ou master si ta branche par défaut s'appelle master
  pull_request:
    branches:
      - main  # ou master

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu la plus récente

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Action pour vérifier le code

    - name: Set up JDK 11
      uses: actions/setup-java@v2  # Installe JDK 11, tu peux modifier selon ton projet
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2  # Met en cache les dépendances pour éviter de les télécharger à chaque fois
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1  # Action officielle de SonarCloud pour GitHub Actions
      with:
        args: >
          -Dsonar.projectKey=<your_project_key>  # Remplace par la clé de ton projet SonarCloud
          -Dsonar.organization=<your_organization>  # Remplace par ton organisation SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Utilisation du secret SONAR_TOKEN que tu as créé précédemment

    - name: Send report via email (optionnel)
      run: |
        echo "Sending email with report"
        # Tu peux ajouter une étape pour envoyer un e-mail avec le rapport ici
